# Generated by Django 3.1.3 on 2020-12-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201201_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='instruments',
            field=models.ManyToManyField(to='users.Instrument'),
        ),
    ]
