# Generated by Django 3.1.3 on 2020-12-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201201_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='generes',
        ),
        migrations.AddField(
            model_name='profile',
            name='generes',
            field=models.ManyToManyField(to='users.Genere'),
        ),
    ]
