# Generated by Django 3.1.3 on 2020-12-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201201_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='open_for_coop',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='type_of_coop',
            field=models.CharField(default='band member', max_length=30),
            preserve_default=False,
        ),
    ]
