# Generated by Django 3.1.3 on 2020-12-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201202_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='type_of_coop',
        ),
        migrations.AddField(
            model_name='profile',
            name='type_of_coop',
            field=models.ManyToManyField(to='users.Cooperation'),
        ),
    ]
