# Generated by Django 3.1.3 on 2020-12-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201202_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='type_of_coop',
            new_name='form_of_coop',
        ),
    ]
