# Generated by Django 3.1.3 on 2020-12-02 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20201202_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='kind',
        ),
        migrations.AddField(
            model_name='profile',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.kindofprofile'),
        ),
    ]
