# Generated by Django 3.1.3 on 2021-01-04 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20201226_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='form_of_coop',
            field=models.ManyToManyField(to='users.UserCooperation'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='generes',
            field=models.ManyToManyField(to='users.UserGenere'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instruments',
            field=models.ManyToManyField(to='users.UserInstrument'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userkindofprofile'),
        ),
    ]
