# Generated by Django 3.1.3 on 2021-01-04 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210104_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-user']},
        ),
    ]
